# ARG VARIANT="ubuntu-20.04"
# ARG VARIANT="ubuntu-latest"
# FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9


ADD klyqa_ctl/*.py /
ADD .git /
ADD klyqa_ctl/requirements.txt /

ENV DEBIAN_FRONTEND=noninteractive

# RUN dpkg --add-architecture i386 && \
    apt-get update && apt-get -y --no-install-recommends install \
    iputils-ping
    # ca-certificates \
    # bzip2 \
    # git \
    # vim-common astyle \
    # wget \
    # tzdata \
    # # python3 \
    # # python3-pip \
    # python3-pyprind \
    # python3-requests \
    # ssh \
    # && \
    # apt-get clean && \
    # rm -rf /var/lib/apt/lists/* && \
    # pip install pycryptodome && \
    # pip install requests && \
    # apt-get clean

ENV TZ=Europe/Berlin

RUN pip3 install --no-cache-dir -r requirements.txt

# RUN git config --global --unset commit.gpgsign
# ENTRYPOINT ["/klyqa-ctl.py"]