
[tool.black]
target-version = ["py39", "py310"]
exclude = 'generated'
experimental-string-processing=true
line-length=79

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true

[tool.flake8]
ignore = "E203,W503"
max-line-length = 80

[tool.pytest.ini_options]
log_cli = true
# log_file_level = DEBUG
addopts = "--ignore=test_code --ignore=klqa2"

log_file = "pytest.log"
# log_file_level = DEBUG