klyqa_ctl::devices::light::commands::ExternalSourceCommand
klyqa_ctl.devices.light.commands.ExternalSourceCommand::ExternalSourceProtocol
klyqa_ctl.devices.light.commands.ExternalSourceCommand::int
TypeJson klyqa_ctl.devices.light.commands.ExternalSourceCommand.json(self)
Return json command.
Referenced by klyqa_ctl.general.general.Command.cloud, klyqa_ctl.general.general.CloudStateCommand.cloud, klyqa_ctl.general.general.Command.msg_str.
bool klyqa_ctl.devices.light.commands.ExternalSourceCommand.check_values(self, Device device)