klyqa_ctl::devices::vacuum::commands
None klyqa_ctl.devices.vacuum.commands.create_device_message(argparse.Namespace args, list[Any] args_in, Callable[[argparse.Namespace], Any] send_to_devices_callable, list[Any] message_queue_tx_local, list[Any] message_queue_tx_command_cloud, list[Any] message_queue_tx_state_cloud)
process_args_to_msg_cleaner
References klyqa_ctl.devices.vacuum.commands.get_command, klyqa_ctl.devices.vacuum.commands.reset_command, klyqa_ctl.devices.vacuum.commands.routine, klyqa_ctl.devices.vacuum.commands.set_command.
None klyqa_ctl.devices.vacuum.commands.get_command(argparse.Namespace args, Callable local_and_cloud_command_msg)
Get command.
Referenced by klyqa_ctl.devices.vacuum.commands.create_device_message.
None klyqa_ctl.devices.vacuum.commands.reset_command(argparse.Namespace args, Callable local_and_cloud_command_msg)
Reset command.
Referenced by klyqa_ctl.devices.vacuum.commands.create_device_message.
None klyqa_ctl.devices.vacuum.commands.set_command(argparse.Namespace args, Callable local_and_cloud_command_msg)
Set command.
Referenced by klyqa_ctl.devices.vacuum.commands.create_device_message.
None klyqa_ctl.devices.vacuum.commands.routine(argparse.Namespace args)
Set routine.
Referenced by klyqa_ctl.devices.vacuum.commands.create_device_message.
None klyqa_ctl.devices.vacuum.commands.add_command_args_cleaner(argparse.ArgumentParser parser)
Add command parse arguments.
Referenced by klyqa_ctl.klyqa_ctl.main.