klyqa_ctl::general::general
int klyqa_ctl::general::general.TRACE
klyqa_ctl::general::general.int
klyqa_ctl::general::general.TypeJson
Referenced by klyqa_ctl.account.Account.get_beared_request_header, klyqa_ctl.account.Account.get_or_create_device.
klyqa_ctl::general::general.str
klyqa_ctl::general::general.float
Referenced by local.connection_handler.LocalConnectionHandler.handle_connection.
klyqa_ctl::general::general.Device_config
Referenced by cloud.CloudBackend.get_device_config.
klyqa_ctl::general::general.ReturnTuple
str klyqa_ctl.general.general.task_name()
Return asyncio task name.
Referenced by klyqa_ctl.general.general.task_log.
tuple[dict | None, bool] klyqa_ctl.general.general.async_json_cache(TypeJson|None json_data, str json_file)
If json data is given write it to cache json_file. Else try to read from json_file the cache.
References klyqa_ctl.general.general.task_log_trace.
Referenced by cloud.CloudBackend.get_device_configs, klyqa_ctl.account_control.AccountControl.load_username_cache, klyqa_ctl.account.Account.login, klyqa_ctl.account_control.AccountControl.login_cache, klyqa_ctl.account.Account.read_acc_settings_cache, klyqa_ctl.account.Account.read_username_cache, klyqa_ctl.account.Account.update_account_settings.
Any | list[str] klyqa_ctl.general.general.get_fields(Any object)
get_fields
Referenced by klyqa_ctl.general.general.get_obj_attr_values_as_string, klyqa_ctl.general.general.get_obj_attrs_as_string.
str klyqa_ctl.general.general.get_obj_attrs_as_string(Any object)
get_obj_attrs_as_string
References klyqa_ctl.general.general.get_fields.
Referenced by klyqa_ctl.klyqa_ctl.Client.select_device.
str klyqa_ctl.general.general.get_obj_attr_values_as_string(Any object)
get_obj_attr_values_as_string
References klyqa_ctl.general.general.get_fields.
Referenced by klyqa_ctl.devices.light.response_status.ResponseStatus.__str__, klyqa_ctl.devices.vacuum.response_status.ResponseStatus.__str__.
Any klyqa_ctl.general.general.format_uid(str text, **Any kwargs)
Referenced by klyqa_ctl.account.Account.cloud_post_to_device, cloud.CloudBackend.send, klyqa_ctl.account.Account.sync_acc_settings_to_controller.
None klyqa_ctl.general.general.set_debug_logger(int level=logging.DEBUG)
Stream logging handler to stderr pipe.
Referenced by klyqa_ctl.klyqa_ctl.main, klyqa_ctl.klyqa_ctl.Client.send_to_devices.
None klyqa_ctl.general.general.task_log(str msg, Callable output_func=LOGGER.info, *Any args, **Any kwargs)
Output task name and logging string.
References klyqa_ctl.general.general.task_name.
Referenced by local.data_package.DataPackage.deserialize, local.connection_handler.LocalConnectionHandler.device_handle_local_tcp, local.connection_handler.LocalConnectionHandler.handle_connection, klyqa_ctl.devices.onboard.Onboard.onboarding_device, local.connection_handler.LocalConnectionHandler.process_aes_initial_vector_package, local.connection_handler.LocalConnectionHandler.process_device_identity_package, local.connection_handler.LocalConnectionHandler.process_message_answer_package, local.connection_handler.LocalConnectionHandler.process_tcp_package, local.connection.TcpConnection.read_local_tcp_socket, local.connection_handler.LocalConnectionHandler.remove_msg_from_queue, klyqa_ctl.general.general.task_log_debug, klyqa_ctl.general.general.task_log_error, klyqa_ctl.general.general.task_log_trace.
None klyqa_ctl.general.general.task_log_debug(str msg, *Any args, **Any kwargs)
Output debug message with task name.
References klyqa_ctl.general.general.task_log.
Referenced by klyqa_ctl.devices.vacuum.response_status.ResponseStatus.__init__, klyqa_ctl.general.general.AsyncIoLock.acquire_within_task, local.connection_handler.LocalConnectionHandler.bind_ports, local.connection_handler.LocalConnectionHandler.check_messages_time_to_live, klyqa_ctl.general.message.Message.check_msg_ttl, klyqa_ctl.account.Account.cloud_post_command_to_dev, local.connection_handler.LocalConnectionHandler.connection_tasks_time_to_live, local.connection_handler.LocalConnectionHandler.device_handle_local_tcp, klyqa_ctl.klyqa_ctl.Client.discover_devices, local.connection_handler.LocalConnectionHandler.discover_devices, local.connection.TcpConnection.encrypt_and_send_msg, cloud.CloudBackend.get_device_config, local.connection_handler.LocalConnectionHandler.handle_connections_task_stop, local.connection_handler.LocalConnectionHandler.handle_incoming_tcp_connection, klyqa_ctl.devices.onboard.Onboard.Lamp_typ, cloud.CloudBackend.load_http_response, klyqa_ctl.klyqa_ctl.main, klyqa_ctl.devices.onboard.Onboard.Onboard_receive, klyqa_ctl.devices.onboard.Onboard.onboarding_device, local.connection_handler.LocalConnectionHandler.process_aes_initial_vector_package, local.connection_handler.LocalConnectionHandler.process_device_identity_package, local.connection_handler.LocalConnectionHandler.process_message_answer_package, local.connection_handler.LocalConnectionHandler.read_incoming_tcp_con_task, local.connection.TcpConnection.read_local_tcp_socket, klyqa_ctl.general.general.AsyncIoLock.release_within_task, klyqa_ctl.devices.device.Device.save_device_message, klyqa_ctl.klyqa_ctl.Client.send_to_devices, klyqa_ctl.klyqa_ctl.Client.send_to_devices_wrapped, local.connection_handler.LocalConnectionHandler.send_udp_broadcast, klyqa_ctl.account.Account.shutdown, local.connection_handler.LocalConnectionHandler.shutdown, local.connection_handler.LocalConnectionHandler.standby, klyqa_ctl.account.Account.update_device_configs, klyqa_ctl.account_control.AccountControl.update_device_configs.
None klyqa_ctl.general.general.task_log_trace(str msg, *Any args, **Any kwargs)
Output debug message with task name.
References klyqa_ctl.general.general.task_log.
Referenced by klyqa_ctl.general.general.async_json_cache, local.connection_handler.LocalConnectionHandler.send_message, klyqa_ctl.general.general.task_log_trace_ex.
None klyqa_ctl.general.general.task_log_error(str msg, *Any args, **Any kwargs)
Output error message with task name.
References klyqa_ctl.general.general.task_log.
Referenced by local.connection_handler.LocalConnectionHandler.device_handle_local_tcp, klyqa_ctl.devices.onboard.Onboard.Onboard_receive, klyqa_ctl.devices.onboard.Onboard.onboarding_device, klyqa_ctl.general.general.AsyncIoLock.release_within_task.
None klyqa_ctl.general.general.task_log_trace_ex()
Log exception trace within task.
References klyqa_ctl.general.general.task_log_trace.
Referenced by local.connection_handler.LocalConnectionHandler.bind_ports, local.connection_handler.LocalConnectionHandler.device_handle_local_tcp, local.connection_handler.LocalConnectionHandler.handle_connection, local.connection_handler.LocalConnectionHandler.read_incoming_tcp_con_task, local.connection.TcpConnection.read_local_tcp_socket, klyqa_ctl.general.general.AsyncIoLock.release_within_task, cloud.CloudBackend.request, cloud.CloudBackend.send, klyqa_ctl.klyqa_ctl.Client.send_to_devices, klyqa_ctl.klyqa_ctl.Client.send_to_devices_wrapped, local.connection_handler.LocalConnectionHandler.send_udp_broadcast, klyqa_ctl.account_control.AccountControl.update_device_configs.