klyqa_ctl::devices::light::commands
tuple[str, int] klyqa_ctl.devices.light.commands.percent_color_message(str red, str green, str blue, str warm, str cold, int transition_time)
Create message for color change in percent.
TypeJson klyqa_ctl.devices.light.commands.external_source_message(int protocol, int port, int channel)
Create external source protocol message.
References cloud.int.
None klyqa_ctl.devices.light.commands.add_command_args_bulb(argparse.ArgumentParser parser)
Add arguments to the argument parser object. Args: parser: Parser object
Referenced by klyqa_ctl.devices.light.commands.discover_devices, klyqa_ctl.klyqa_ctl.main.
argparse.Namespace | None klyqa_ctl.devices.light.commands.discover_devices(argparse.Namespace args, list[Any] args_in, Callable[[argparse.Namespace], Any] send_to_devices_cb)
Send out klyqa broadcast to discover all devices. Tries to set device_unitids in args parse. The user can select them. Params: args (Argsparse): Parsed args object args_in (list): List of arguments parsed to the script call timeout_ms (int, optional): Timeout to send. Defaults to 5000. Raises: Exception: Network or file errors Returns: bool: True if succeeded.
References klyqa_ctl.devices.light.commands.add_command_args_bulb, klyqa_ctl.general.parameters.add_config_args, klyqa_ctl.general.parameters.get_description_parser.
bool klyqa_ctl.devices.light.commands.add_device_command_to_queue(argparse.Namespace args, list[Any] args_in, Callable[[argparse.Namespace], Any] send_to_devices_callable, list[Command] msg_queue, list[str] scene_list)
Process arguments for communicating with lights. Fill message queues for local and cloud communication. Discover devices to communicate with. Params: args: Parsed arguments to be processed. args_in: Original arguments as a list, if we want to reparse and add arguments. send_to_devices_callable: If we need to send something to the lamps, use this callable. message_queue_tx_local: Queue to be filled with messages for local communication. message_queue_tx_command_cloud: Queue for cloud command messages. message_queue_tx_state_cloud: Queue for cloud state messages. scene_list: If a scene is applied, add it to the scene list, so the klyqa-ctl send function can process it.
References klyqa_ctl.devices.light.commands.command_brightness, klyqa_ctl.devices.light.commands.command_color, klyqa_ctl.devices.light.commands.commands_select, klyqa_ctl.devices.light.commands.enable_tb, cloud.int, klyqa_ctl.devices.light.commands.routine_scene.
bool klyqa_ctl.devices.light.commands.commands_select(argparse.Namespace args, list[str] args_in, Callable send_to_devices_callable)
Interactive command select.
Referenced by klyqa_ctl.devices.light.commands.add_device_command_to_queue.
None klyqa_ctl.devices.light.commands.command_color(argparse.Namespace args, list[Command] msg_queue)
Command for setting the color.
References cloud.int.
Referenced by klyqa_ctl.devices.light.commands.add_device_command_to_queue.
None klyqa_ctl.devices.light.commands.command_brightness(argparse.Namespace args, list[Command] msg_queue)
Command for brightness.
References cloud.int.
Referenced by klyqa_ctl.devices.light.commands.add_device_command_to_queue.
None klyqa_ctl.devices.light.commands.command_temperature(argparse.Namespace args, list[Command] msg_queue)
Command for temperature.
References cloud.int.
bool klyqa_ctl.devices.light.commands.routine_scene(argparse.Namespace args, list[str] scene_list)
Command for select scene.
Referenced by klyqa_ctl.devices.light.commands.add_device_command_to_queue.
None klyqa_ctl.devices.light.commands.enable_tb(argparse.Namespace args, list[Command] msg_queue)
Enable thingsboard to device.
Referenced by klyqa_ctl.devices.light.commands.add_device_command_to_queue.
bool klyqa_ctl.devices.light.commands.forced_continue(bool force, str reason)
Force argument.
Referenced by klyqa_ctl.devices.light.commands.ColorCommand.check_values, klyqa_ctl.devices.light.commands.TemperatureCommand.check_values, klyqa_ctl.devices.light.commands.BrightnessCommand.check_values, klyqa_ctl.devices.light.commands.RoutinePutCommand.check_values, klyqa_ctl.devices.light.commands.missing_config.
bool klyqa_ctl.devices.light.commands.missing_config(bool force, str product_id)
Missing device config.
References klyqa_ctl.devices.light.commands.forced_continue.
Referenced by klyqa_ctl.devices.light.commands.ColorCommand.check_values, klyqa_ctl.devices.light.commands.TemperatureCommand.check_values, klyqa_ctl.devices.light.commands.BrightnessCommand.check_values, klyqa_ctl.devices.light.commands.RoutinePutCommand.check_values.