klyqa_ctl::general::parameters
argparse.ArgumentParser klyqa_ctl.general.parameters.get_description_parser()
Make an argument parse object.
Referenced by klyqa_ctl.devices.light.commands.discover_devices, klyqa_ctl.klyqa_ctl.main, klyqa_ctl.klyqa_ctl.Client.send_to_devices.
None klyqa_ctl.general.parameters.add_config_args(argparse.ArgumentParser parser)
Add arguments to the argument parser object. Args: parser: Parser object
Referenced by klyqa_ctl.devices.light.commands.discover_devices, klyqa_ctl.klyqa_ctl.main, klyqa_ctl.klyqa_ctl.Client.send_to_devices.